version: "3.0"  # optional since v1.27.0
services:
  db:
    image: postgres:11.14-bullseye
    # image: postgres
    restart: always
    ports:
      - 9102:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  job:
    build:
      context: ..
      dockerfile: docker/Job/Job.Dockerfile
    env_file:
      - Job/local.env
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  api:
    build:
      context: ..
      dockerfile: docker/Api/Api.Dockerfile
    ports:
      - 9002:80
    env_file:
      - Api/local.env