version: "3.0"  # optional since v1.27.0
services:
  db:
    image: postgres:11.14-bullseye
    # image: postgres
    restart: always
    ports:
      - 9102:5432
    volumes:
      - "./../data/scripts:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
  job:
    build:
      context: ..
      dockerfile: docker/Job/Job.Dockerfile
    env_file:
      - Job/local.env
    links:
      - db
    depends_on:
      - db
    environment:
      TZ: America/Sao_Paulo
  api:
    build:
      context: ..
      dockerfile: docker/Api/Api.Dockerfile
    ports:
      - 9002:80
      - 9003:443
    depends_on:
      - db
    env_file:
      - Api/local.env
    environment:
      TZ: America/Sao_Paulo